version: '3'
services:
  smashing:
    build: .
    image: docker.releaseapp.io/tmcclung/dockerfile-smashing
    command:
      - /run.sh
    ports:
      - "3030:3030"
    environment:
      - PORT=3030

