version: '3'
services:
  smashing:
    image: 232490755822.dkr.ecr.us-west-2.amazonaws.com/tmcclung/smashing
    command:
      - run.sh
    ports:
      - "3030:3030"
    environment:
      - PORT=3030

